name: 画像圧縮

on:
  pull_request:
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.gif'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
